using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DbUp.Engine
{
    /// <summary>
    /// This interface is implemented by classes that provide script hashing  
    /// </summary>
    public interface IHasher
    {
        /// <summary>
        /// Generates hash from input string
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        string GenerateHash(string input);
        /// <summary>
        /// Verifies if hash was generated by this hasher
        /// </summary>
        /// <param name="hash"></param>
        /// <returns></returns>
        bool Verify(string hash);

    }
}
