using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace DbUp.Engine.Hashers
{
    /// <summary>
    /// Hash inputs using MD5 algorithm with additionaly mark at the beginning to verify if hash was generated by this class
    /// </summary>
    public class Md5WithMarkHasher : IHasher
    {
        private const string Salt = "MD5alg_";
        private readonly MD5 hashProvider;

        /// <summary>
        /// Hash inputs using MD5 algorithm
        /// </summary>
        public Md5WithMarkHasher()
        {
            hashProvider = MD5.Create();
        }

        /// <summary>
        /// Generates hash from provided input
        /// </summary>
        /// <param name="input"></param>
        /// <returns></returns>
        public string GenerateHash(string input)
        {
            var bytes = Encoding.UTF8.GetBytes(input);
            var hash = hashProvider.ComputeHash(bytes);

            return string.Format("{0}{1}", Salt, Convert.ToBase64String(hash));
        }

        /// <summary>
        /// Verifies if hash was generated by this hasher
        /// </summary>
        /// <param name="hash"></param>
        /// <returns></returns>
        public bool Verify(string hash)
        {
            return hash.StartsWith(Salt);
        }
    }
}
